#pragma once

enum class MoveType : int
{
    PLAYER_SITTING_IDLING = 5,
    PLAYER_SITTING_WALKING_LEFT = 7,
    PLAYER_SITTING_WALKING_RIGHT = 8,
    PLAYER_SITTING_WALKING_BACK = 9,
    PLAYER_SITTING_WALKING_FORWARD = 10,
    PLAYER_IDLING = 11,
    PLAYER_WALKING = 12,
    PLAYER_RUNNING = 13,
    PLAYER_CRYING = 14,
    PLAYER_BITE = 15,
    PLAYER_BITE_STOP = 16,
    PLAYER_TO_CRYING = 17,
    PLAYER_FROM_CRYING = 18,
    PLAYER_TO_ANGRY = 19,
    PLAYER_TO_WALK = 20,
    PLAYER_FROM_WALK = 21,
};
